### PR TITLE
Homework 6 help

### PR DESCRIPTION
**Pull request by artgonzalezacc**
Didn't validate dna strings for length of 10

### CODE REVIEW

**Comment by MJBrady13** [comment]
I thought we didn't need to validate and we were to assume the data would be entered correctly. I thought I saw you say validation wasn't needed in a post on the discussion board. My fault if I misunderstood. Thank you for the corrections.

**Comment by artgonzalezacc** [comment]
That was for limtiing text characters to A,C,G or T.

**Comment by MJBrady13** [comment]
She didn't ask specifically about validating letters, she asked generally
about validation. In her example, she even just had the input say: 'Enter
DNA string with length of 10, range of A, C, G and T'
Your response was "There's no need to validate the data". In my code, I
say: 'Enter DNA string 1 (length 10, A,C,G,T only!)'
I don't understand the difference.

**Comment by artgonzalezacc** [comment]
It's 5 points, if it costs you an A send me this email.

Thanks

**Pull request merged**
